language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t cncubukcu/docker-react -f Dockerfile.dev .

script:
  - docker run cncubukcu/docker-react yarn test -- --coverage